### ISSUE TITLE
PyDisdrometer Roadmap

### ISSUE THREAD

**Issue by josephhardinee** [josephhardinee/PyDisdrometer#24]
After talking with @nguy  the following represents what we see as the roadmap to getting PyDisdrometer to a V1 release. 

- [ ] File Saving ( Will standardize a format, netcdf Based). 
- [ ] All Readers Consistent syntax and internal structure.
- [ ] Standard Plotting Routines setup
- [ ]  Documentation and Cookbook examples finalized
- [ ] Masked arrays for fields.  
- [ ] Rename to PyDSD to represent the larger number of instruments we will support
- [ ] Readers moved into .io
- [ ] All fields more consistent with labeling(Dictionary Syntax)
- [ ] Documentation Generation in Travis-CI
- [ ] Arbitrary Dielectric Scattering/Temperature.

I'm sure I'm missing a few things. Nick, if you want to comment on anything else I'll add it to the list.

**Comment by nguy** [comment]
I would say the readers to have consistent core structure with the ability to be extendable.

Also and expansion of DSD parameter calculations.
